In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal
import csv


from keras.layers import Input, Dense
from keras.models import Model
from numpy import linalg as LA
import sklearn
from sklearn import metrics
from scipy.signal import find_peaks
from numpy import asarray
from numpy import savetxt

Using TensorFlow backend.


In [4]:

def pad(l, content, width):
    l.extend([content] * (width - len(l)))
    return l


usr_dir="Data_files/"
for user in range(1,23,1):
    data=[]
    usr_file=usr_dir+"U"+str(user)+"_LIHF_itd_file.csv"
    
    
    happy_bucket=[]
    sad_bucket=[]
    stressed_bucket=[]
    relax_bucket=[]
    
    happy_list=[]
    sad_list=[]
    stressed_list=[]
    relax_list=[]
    
    window_size=50
    
    print(usr_file)
    dataset=pd.read_csv(usr_file,header=None)
    dataframe=dataset.values
    
    #print("row_number="+str(dataframe.shape[0]))
    
    # value list holds unique id 
    value_list=[]
    for i in range(dataframe.shape[0]):
        value_list.append(dataframe[i][0])
        
    ID_list=list(set(value_list))
    ID_list.sort()
    print("number of unique ID="+str(len(ID_list)))
    start=0
    next_start=0
    # traverse the whole list and add list of ITD values in emotion list
    for i in range(len(ID_list)):
        ID_number=ID_list[i]
        #print("ID_number="+str(ID_number))
        ITD_values=[]
        
        for j in range(start,dataframe.shape[0],1):
            if(dataframe[j][0]==ID_number):
                ITD_values.append(dataframe[j][2])
                next_start=next_start+1
            else:
                start=next_start
                #print(next_start)
                break
        if(dataframe[j-1][4]==2 and len(ITD_values)>3):
             happy_bucket.append(list(ITD_values))
        if(dataframe[j-1][4]==-2 and len(ITD_values)>3):
             sad_bucket.append(list(ITD_values))
        if(dataframe[j-1][4]==1 and len(ITD_values)>3):
             stressed_bucket.append(list(ITD_values))
        if(dataframe[j-1][4]==0 and len(ITD_values)>3):
            relax_bucket.append(list(ITD_values))
    print("sum of bucket length="+str(len(happy_bucket)+len(sad_bucket)+len(stressed_bucket)+len(relax_bucket)))
    count_ITD_list=len(happy_bucket)+len(sad_bucket)+len(stressed_bucket)+len(relax_bucket)
    ########################################################
    
    for i in range(len(happy_bucket)):
        #print("happy_bucket="+str(i)+","+"length="+str(len(happy_bucket[i])))
        for j in range(0,len(happy_bucket[i]),window_size):
            if(j+window_size<len(happy_bucket[i])):
                happy_list.append(list(happy_bucket[i][j:j+window_size]))
                #print(happy_bucket[i][j:j+window_size])
                
            #else:
                #number_zero=(j+window_size)-len(happy_bucket[i])
                #happy_list.append(list(pad(happy_bucket[i][j:len(happy_bucket[i])],0,number_zero)))
                #print(pad(happy_bucket[i][j:len(happy_bucket[i])],0,number_zero))
                
    for i in range(len(sad_bucket)):
        #print("sad_bucket="+str(i)+","+"length="+str(len(sad_bucket[i])))
        for j in range(0,len(sad_bucket[i]),window_size):
            if(j+window_size<len(sad_bucket[i])):
                sad_list.append(list(sad_bucket[i][j:j+window_size]))
                #print(sad_bucket[i][j:j+window_size])   
                
    for i in range(len(stressed_bucket)):
        #print("stress_bucket="+str(i)+","+"length="+str(len(stressed_bucket[i])))
        for j in range(0,len(stressed_bucket[i]),window_size):
            if(j+window_size<len(stressed_bucket[i])):
                stressed_list.append(list(stressed_bucket[i][j:j+window_size]))
                #print(stressed_bucket[i][j:j+window_size])            
    
    for i in range(len(relax_bucket)):
        #print("relax_bucket="+str(i)+","+"length="+str(len(relax_bucket[i])))
        for j in range(0,len(relax_bucket[i]),window_size):
            if(j+window_size<len(relax_bucket[i])):
                relax_list.append(list(relax_bucket[i][j:j+window_size]))
                #print(relax_bucket[i][j:j+window_size])    
                
    for i in range(len(happy_list)):
        # peak amplitude list
        peak_list=[]
        freq_list=[]
        gap_list=[]
        # signal
        signal=np.array(happy_list[i],dtype=float)
        # taking absolute value after fft
        sp=np.abs(np.fft.fft(signal))
        # frequency from fft
        freq=np.fft.fftfreq(sp.size)
        # indicies for peaks
        peaks,_=find_peaks(sp)
        for i in range(len(peaks)):
            peak_list.append(sp[peaks[i]])
            freq_list.append(freq[peaks[i]])
            
        peak_list=np.array(peak_list)
        freq_list=np.array(freq_list)
        #ind = np.argpartition(peak_list, -3)[-3:]
        #print(peak_list)
        
        # find indices of top most amplitude in sorted order
        ind=peak_list.argsort()[-3:][::-1]
        #print(peak_list[ind])
        print(freq_list[ind])
        # concatenate peak amplitude and frequency
        print(peak_list[ind])
        for val in ind:
            gap_list.append(peaks[val])
        gap_list.sort()
        
        print(gap_list)
        
        for k in range(len(gap_list)-1):
            gap_list[k]=gap_list[k+1]-gap_list[k]
        if(len(gap_list)!=0):
            gap_list.remove(gap_list[-1])
        #gap_list.append(2)
        #print(freq[ind])
        row=np.concatenate((peak_list[ind],freq_list[ind]))
        temp=np.append(row,gap_list).tolist()
        if(len(temp)<8):
            temp=pad(temp,0,8)
        temp.append(2)    
        data.append(temp)
        # whole data is collected in data
        
        #print("peak list length in Happy="+str(peak_list[ind].size))
        #for k in range(peak_list[ind].size):
            #index=sp[peak_list[k]]
        
        
    for i in range(len(sad_list)):
        peak_list=[]
        freq_list=[]
        gap_list=[]
        signal=np.array(sad_list[i],dtype=float)
        sp=np.abs(np.fft.fft(signal))
        freq=np.fft.fftfreq(sp.size)
        peaks,_=find_peaks(sp)
        for i in range(len(peaks)):
            peak_list.append(sp[peaks[i]])
            freq_list.append(freq[peaks[i]])
        peak_list=np.array(peak_list)
        freq_list=np.array(freq_list)
        #ind = np.argpartition(peak_list, -3)[-3:]
        #print(peak_list)
        ind=peak_list.argsort()[-3:][::-1]
        
        for val in ind:
            gap_list.append(peaks[val])
        gap_list.sort()  
        print(gap_list)
        for k in range(len(gap_list)-1):
            gap_list[k]=gap_list[k+1]-gap_list[k]
        if(len(gap_list)!=0):
            gap_list.remove(gap_list[-1])
        #gap_list.append(-2)
        #print(peak_list[ind])
        #print(freq[ind])
        row=np.concatenate((peak_list[ind],freq_list[ind]))
        temp=np.append(row,gap_list).tolist()
        if(len(temp)<8):
            temp=pad(temp,0,8)
        temp.append(-2)    
        data.append(temp)
        
    for i in range(len(stressed_list)):
        peak_list=[]
        freq_list=[]
        gap_list=[]
        signal=np.array(stressed_list[i],dtype=float)
        sp=np.abs(np.fft.fft(signal))
        freq=np.fft.fftfreq(sp.size)
        peaks,_=find_peaks(sp)
        for i in range(len(peaks)):
            peak_list.append(sp[peaks[i]])
            freq_list.append(freq[peaks[i]])
        peak_list=np.array(peak_list)
        freq_list=np.array(freq_list)
        #ind = np.argpartition(peak_list, -3)[-3:]
        #print(peak_list)
        ind=peak_list.argsort()[-3:][::-1]
        for val in ind:
            gap_list.append(peaks[val])
        gap_list.sort()  
        print(gap_list)
        for k in range(len(gap_list)-1):
            gap_list[k]=gap_list[k+1]-gap_list[k]
        if(len(gap_list)!=0):
            
            gap_list.remove(gap_list[-1])
        #gap_list.append(1)
        #print(peak_list[ind])
        #print(freq[ind])
        row=np.concatenate((peak_list[ind],freq_list[ind]))
        temp=np.append(row,gap_list).tolist()
        if(len(temp)<8):
            temp=pad(temp,0,8)
        temp.append(1)    
        data.append(temp)
        
    for i in range(len(relax_list)):
        peak_list=[]
        freq_list=[]
        gap_list=[]
        signal=np.array(relax_list[i],dtype=float)
        sp=np.abs(np.fft.fft(signal))
        freq=np.fft.fftfreq(sp.size)
        peaks,_=find_peaks(sp)
        for i in range(len(peaks)):
            peak_list.append(sp[peaks[i]])
            freq_list.append(freq[peaks[i]])
        peak_list=np.array(peak_list)
        freq_list=np.array(freq_list)
        #ind = np.argpartition(peak_list, -3)[-3:]
        #print(peak_list)
        ind=peak_list.argsort()[-3:][::-1]
        #print(peak_list[ind])
        #print(freq[ind])
        for val in ind:
            gap_list.append(peaks[val])
        gap_list.sort()  
        print(gap_list)
        for k in range(len(gap_list)-1):
            gap_list[k]=gap_list[k+1]-gap_list[k]
        if(len(gap_list)!=0):
            
            gap_list.remove(gap_list[-1])
        #gap_list.append(0)
        row=np.concatenate((peak_list[ind],freq_list[ind]))
        temp=np.append(row,gap_list).tolist()
        if(len(temp)<8):
            temp=pad(temp,0,8)
        temp.append(0)    
        data.append(temp)  
            
    #print(data)        
    #data=asarray(data)
    data_file="Raw_data_Freq/Amp_window/"+"U"+str(user)+"_LIHF_itd_file.csv"
    with open(data_file,"w") as resultfile:
        writer=csv.writer(resultfile)
        writer.writerows(data)
        
    

Data_files/U1_LIHF_itd_file.csv
number of unique ID=114
sum of bucket length=114
[ 0.48 -0.48  0.3 ]
[11.20307292 11.20307292  6.52123368]
[15, 24, 26]
[-0.42  0.42 -0.5 ]
[8.67818479 8.67818479 7.489     ]
[21, 25, 29]
[ 0.46 -0.46 -0.42]
[7.26762292 7.26762292 6.30166948]
[23, 27, 29]
[-0.3   0.3  -0.04]
[5.36041382 5.36041382 4.42343657]
[15, 35, 48]
[ 0.46 -0.46  0.26]
[21.05997144 21.05997144 19.37825015]
[13, 23, 27]
[-0.06  0.06  0.48]
[9.22994314 9.22994314 8.49486074]
[3, 24, 47]
[ 0.18 -0.18 -0.04]
[7.03749623 7.03749623 5.94080853]
[9, 41, 48]
[-0.32  0.32  0.14]
[14.52498157 14.52498157 13.19879057]
[7, 16, 34]
[-0.48  0.48  0.44]
[11.43349736 11.43349736 10.61241392]
[22, 24, 26]
[ 0.24 -0.24 -0.1 ]
[8.1982589  8.1982589  8.08616788]
[12, 38, 45]
[-0.1   0.1   0.36]
[14.50598824 14.50598824 14.20570794]
[5, 18, 45]
[ 0.44 -0.44 -0.04]
[23.31572716 23.31572716 21.68928255]
[22, 28, 48]
[ 0.46 -0.46  0.36]
[16.65278296 16.65278296 15.67721687]
[18, 23, 27]
[-0.42  0.42 -0.5 

[19, 31, 40]
[7, 16, 34]
[21, 25, 29]
[10, 29, 40]
[20, 30, 32]
[7, 24, 26]
[8, 23, 42]
[19, 31, 35]
[19, 25, 31]
[20, 30, 44]
[18, 21, 29]
[21, 23, 27]
[19, 31, 48]
[16, 26, 34]
[15, 17, 33]
[19, 21, 29]
[21, 29, 35]
[8, 21, 29]
[20, 25, 30]
[18, 22, 32]
[20, 25, 30]
[13, 28, 37]
[4, 31, 46]
[9, 28, 41]
[17, 31, 33]
[18, 27, 32]
Data_files/U2_LIHF_itd_file.csv
number of unique ID=45
sum of bucket length=45
[ 0.42 -0.42 -0.14]
[3.73800114 3.73800114 3.33156572]
[21, 29, 43]
[-0.32  0.32 -0.38]
[5.02559064 5.02559064 4.42945684]
[16, 31, 34]
[-0.5  -0.42  0.42]
[2099.617      2093.84152472 2093.84152472]
[21, 25, 29]
[-0.4   0.4   0.06]
[11.044202   11.044202   10.67483545]
[3, 20, 30]
[ 0.34 -0.34 -0.4 ]
[9.8469574  9.8469574  9.79009005]
[17, 30, 33]
[-0.22  0.22  0.46]
[54.12336055 54.12336055 51.6132781 ]
[11, 23, 39]
[-0.5  -0.28  0.28]
[4.761      4.40362024 4.40362024]
[14, 25, 36]
[-0.16  0.16 -0.26]
[3.59216859 3.59216859 3.44736737]
[8, 37, 42]
[-0.34  0.34 -0.3 ]
[72.54310907

[5, 8, 45]
[11, 15, 39]
[14, 36, 40]
[7, 15, 43]
[3, 25, 47]
[9, 17, 41]
[15, 18, 35]
[12, 19, 38]
[19, 28, 31]
[18, 32, 36]
[16, 29, 34]
[17, 33]
[6, 22, 44]
[8, 21, 29]
[22, 25, 28]
[9, 34, 41]
[11, 19, 31]
[13, 25, 37]
[2, 18, 48]
[13, 32, 37]
[19, 31, 40]
[7, 16, 34]
[21, 25, 29]
[10, 29, 40]
[20, 30, 32]
[7, 24, 26]
[8, 23, 42]
[19, 31, 35]
[14, 36, 43]
[15, 26, 35]
[21, 25, 29]
[19, 25, 31]
[20, 30, 44]
[18, 21, 29]
[21, 23, 27]
[19, 31, 48]
[16, 26, 34]
[15, 17, 33]
[19, 21, 29]
Data_files/U4_LIHF_itd_file.csv
number of unique ID=118
sum of bucket length=118
[-0.44  0.44 -0.06]
[201.72705284 201.72705284 198.09330915]
[22, 28, 47]
[-0.5 -0.2  0.2]
[3.148      2.92616491 2.92616491]
[10, 25, 40]
[-0.26  0.26 -0.4 ]
[27.16971414 27.16971414 23.78276756]
[13, 30, 37]
[ 0.3  -0.3  -0.44]
[23.85996292 23.85996292 22.06927081]
[15, 28, 35]
[-0.24  0.24  0.48]
[42.55884833 42.55884833 40.22543706]
[12, 24, 38]
[-0.26  0.26 -0.32]
[65.39353239 65.39353239 64.57870252]
[13, 34, 37]
[-0.3

[5, 40, 45]
[23, 27, 31]
[21, 25, 29]
[10, 26, 40]
[4, 23, 27]
[20, 25, 30]
[13, 23, 37]
[11, 25, 39]
[5, 7, 45]
[3, 41, 47]
[2, 16, 34]
[10, 25, 40]
[11, 22, 28]
[21, 29, 32]
[24, 26, 48]
[11, 29, 39]
[2, 27, 48]
[8, 19, 31]
[18, 32, 36]
[7, 31, 43]
[3, 5, 47]
[10, 24, 40]
[15, 30, 35]
[12, 24, 38]
[22, 28, 39]
[23, 27, 39]
[9, 29, 41]
[19, 31, 45]
[9, 41, 45]
[14, 20, 36]
[13, 37, 48]
[19, 31, 47]
[23, 25, 27]
[2, 5, 48]
[20, 30, 34]
[4, 43, 46]
[12, 26, 38]
[14, 27, 36]
[11, 39, 43]
[16, 34, 40]
[2, 30, 48]
[12, 24, 26]
[13, 26, 37]
[17, 25, 33]
[9, 22, 28]
[16, 21, 29]
[7, 14, 43]
[13, 15, 35]
[13, 37, 40]
[11, 20, 30]
[4, 37, 46]
[9, 25, 41]
[17, 31, 33]
[24, 26, 33]
[13, 15, 35]
[11, 25, 39]
[17, 26, 33]
[11, 28, 39]
[5, 27, 45]
[7, 12, 43]
[22, 28, 45]
Data_files/U5_LIHF_itd_file.csv
number of unique ID=66
sum of bucket length=66
[-0.06  0.06 -0.1 ]
[3.85803943 3.85803943 3.51484757]
[3, 45, 47]
[-0.16  0.16 -0.08]
[4.35954595 4.35954595 4.06923012]
[8, 42, 46]
[-0.46  0.46 -0.1

number of unique ID=49
sum of bucket length=49
[-0.32  0.32  0.46]
[6.48415433 6.48415433 4.07978247]
[16, 23, 34]
[-0.34  0.34 -0.28]
[5.09977169 5.09977169 2.96740573]
[17, 33, 36]
[-0.4   0.4  -0.44]
[4.56473111 4.56473111 4.36682565]
[20, 28, 30]
[-0.44  0.44  0.24]
[4.92510214 4.92510214 4.70116769]
[12, 22, 28]
[-0.32  0.32 -0.2 ]
[5.49781487 5.49781487 4.36525273]
[16, 34, 40]
[-0.38  0.38 -0.24]
[4.76270795 4.76270795 3.40082103]
[19, 31, 38]
[-0.44  0.44  0.34]
[4.42882399 4.42882399 3.90901986]
[17, 22, 28]
[ 0.12 -0.12 -0.36]
[9.4911522  9.4911522  8.54192809]
[6, 32, 44]
[-0.36  0.36 -0.42]
[4.70227969 4.70227969 3.71802211]
[18, 29, 32]
[-0.38  0.38  0.18]
[3.32109551 3.32109551 1.99522108]
[9, 19, 31]
[-0.38  0.38  0.44]
[4.02816138 4.02816138 3.71256507]
[19, 22, 31]
[-0.3   0.3  -0.46]
[2.74235167 2.74235167 2.72570083]
[15, 27, 35]
[-0.28  0.28 -0.36]
[4.73183447 4.73183447 4.4444585 ]
[14, 32, 36]
[-0.36  0.36  0.28]
[4.33506873 4.33506873 3.63950749]
[14, 18, 32]
[-0

number of unique ID=89
sum of bucket length=89
[-0.26  0.26 -0.38]
[4.18135655 4.18135655 4.0277935 ]
[13, 31, 37]
[-0.5  -0.26  0.26]
[5.504      4.37364147 4.37364147]
[13, 25, 37]
[-0.5  -0.26  0.26]
[3.167      2.08310208 2.08310208]
[13, 25, 37]
[-0.44  0.44  0.22]
[274.524756   274.524756   272.51327241]
[11, 22, 28]
[-0.46  0.46 -0.4 ]
[14.37093993 14.37093993 14.33367755]
[23, 27, 30]
[-0.4  0.4 -0.2]
[19.76335668 19.76335668 19.05707335]
[20, 30, 40]
[ 0.22 -0.22  0.28]
[124.62200278 124.62200278 123.47592164]
[11, 14, 39]
[-0.04  0.04  0.22]
[79.49493956 79.49493956 79.01244545]
[2, 11, 48]
[-0.5  -0.06  0.06]
[3.189      2.66706965 2.66706965]
[3, 25, 47]
[-0.5  0.3 -0.3]
[23.645      21.37410131 21.37410131]
[15, 25, 35]
[-0.42  0.42  0.06]
[8.08559007 8.08559007 7.03384519]
[3, 21, 29]
[-0.5]
[40.915]
[25]
[-0.2   0.2  -0.06]
[17.46236173 17.46236173 16.81673991]
[10, 40, 47]
[-0.08  0.08 -0.42]
[16.9327253  16.9327253  15.72500864]
[4, 29, 46]
[-0.28  0.28 -0.18]
[5.62615

number of unique ID=54
sum of bucket length=54
[20, 30, 40]
[4, 32, 46]
[7, 36, 43]
[23, 25, 27]
[22, 28, 33]
[13, 26, 37]
[6, 10, 40]
[14, 36, 38]
[24, 26, 33]
[20, 30, 40]
[2, 43, 48]
[18, 32, 46]
[10, 27, 40]
[12, 38, 40]
[11, 25, 39]
[22, 28, 39]
[12, 38, 41]
[12, 18, 38]
[16, 18, 32]
[23, 27, 37]
[16, 20, 34]
[6, 40, 44]
[5, 39, 45]
[13, 24, 37]
[2, 6, 44]
[12, 38, 45]
[6, 25, 44]
[2, 45, 48]
[13, 25, 37]
[24, 26, 38]
[13, 25, 37]
[19, 31, 40]
[10, 30, 40]
[17, 29, 33]
[4, 27, 46]
[19, 28, 31]
[11, 25, 39]
[13, 33, 37]
[20, 25, 30]
[10, 40, 46]
[4, 34, 46]
[14, 25, 36]
[13, 25, 37]
[5, 40, 45]
[17, 31, 33]
[16, 18, 32]
[8, 16, 42]
[9, 16, 41]
[12, 38, 42]
[13, 24, 37]
[24, 26, 48]
[5, 43, 45]
[20, 30, 40]
[5, 15, 35]
[6, 39, 44]
[10, 40, 47]
[11, 25, 39]
[16, 32, 34]
[4, 25, 46]
[4, 29, 46]
[9, 25, 41]
[11, 22, 28]
[3, 26, 47]
[19, 31, 38]
[11, 19, 31]
[8, 25, 42]
[14, 18, 32]
[3, 42, 47]
[18, 25, 32]
[5, 45, 47]
[5, 25, 45]
[17, 25, 33]
[12, 25, 38]
[20, 25, 30]
[2, 11, 39]
[7, 2

[22, 28, 30]
[22, 28, 43]
[18, 32, 36]
[17, 22, 28]
[21, 29, 37]
[10, 21, 29]
[13, 24, 26]
[16, 34, 47]
[23, 27, 44]
[5, 33, 45]
[8, 42, 46]
[8, 20, 30]
[17, 28, 33]
[21, 25, 29]
[19, 27, 31]
[20, 30, 32]
[6, 10, 40]
[18, 21, 29]
[11, 16, 39]
[10, 19, 40]
[18, 25, 32]
[12, 25, 38]
[23, 27, 32]
[10, 40, 48]
[10, 25, 40]
[5, 10, 45]
[14, 18, 32]
[9, 30, 41]
[6, 25, 44]
[11, 18, 39]
[3, 21, 47]
[22, 28, 37]
[6, 19, 31]
[22, 25, 28]
[15, 25, 35]
[8, 11, 39]
[17, 19, 31]
[8, 31, 42]
[7, 14, 36]
[23, 25, 27]
[12, 29, 38]
[19, 31, 47]
[12, 35, 38]
[4, 37, 46]
[22, 28, 37]
[12, 28, 38]
[11, 39, 48]
[11, 33, 39]
[12, 23, 38]
[14, 36, 44]
[11, 39, 44]
[13, 24, 37]
[17, 33, 45]
[19, 27, 31]
[4, 6, 46]
[24, 26, 35]
[2, 33, 48]
[13, 37, 48]
[22, 28, 37]
[2, 4, 48]
[22, 28, 30]
[3, 26, 47]
[19, 31, 38]
[2, 34, 48]
[15, 26, 35]
[15, 35, 37]
[13, 37, 47]
[11, 25, 39]
[10, 14, 40]
[7, 9, 41]
[2, 45, 48]
[11, 16, 34]
[18, 25, 32]
[10, 13, 40]
[14, 28, 36]
[2, 17, 33]
[17, 22, 28]
[24, 26, 40]
[16, 32, 3

[7, 19, 43]
[18, 25, 32]
[19, 31, 34]
[14, 25, 36]
[2, 46, 48]
[18, 21, 32]
[2, 25, 48]
[20, 28, 30]
[21, 25, 29]
[14, 33, 36]
[11, 25, 39]
[24, 26, 31]
[12, 36, 38]
[21, 29, 36]
[10, 38, 40]
[19, 22, 31]
[22, 25, 28]
[18, 32, 36]
[17, 27, 33]
[16, 25, 34]
[11, 39, 42]
[19, 25, 31]
[22, 28, 35]
[5, 32, 45]
[5, 21, 45]
[11, 17, 33]
[8, 21, 29]
[8, 16, 34]
[7, 29, 43]
[19, 31, 34]
[3, 28, 47]
[11, 33, 39]
[11, 31, 39]
[5, 33, 45]
[6, 44, 47]
[9, 25, 41]
[2, 25, 48]
[5, 25, 45]
[3, 5, 47]
[5, 39, 45]
[8, 37, 42]
[20, 30, 40]
[23, 27, 31]
[19, 25, 31]
[20, 30, 44]
[2, 5, 45]
[15, 35, 48]
[16, 32, 34]
[19, 25, 31]
[15, 22, 28]
[23, 27, 47]
[20, 30, 33]
[11, 30, 39]
[3, 43, 47]
[7, 11, 39]
[6, 28, 44]
[4, 6, 44]
[19, 29, 31]
[4, 29, 46]
[3, 23, 27]
[7, 43, 48]
[5, 13, 45]
[6, 27, 44]
[12, 35, 38]
[9, 36, 41]
[6, 34, 44]
[21, 25, 29]
[4, 11, 46]
[16, 29, 34]
[6, 35, 44]
[13, 24, 37]
[10, 40, 47]
[12, 18, 38]
[15, 22, 35]
[10, 40, 47]
[10, 40, 42]
[14, 36, 44]
[10, 23, 27]
[23, 27, 35]
[18, 32

Data_files/U13_LIHF_itd_file.csv
number of unique ID=68
sum of bucket length=67
[-0.5  -0.28  0.28]
[52.772      51.77602061 51.77602061]
[14, 25, 36]
[-0.5  -0.22  0.22]
[114.109     95.585839  95.585839]
[11, 25, 39]
[-0.44  0.44 -0.24]
[15.92894276 15.92894276 13.85375967]
[22, 28, 38]
[-0.5  -0.18  0.18]
[107.977      100.57431938 100.57431938]
[9, 25, 41]
[ 0.14 -0.14 -0.36]
[40.62565519 40.62565519 40.53681905]
[7, 32, 43]
[-0.04  0.04 -0.08]
[43.65068011 43.65068011 41.49371889]
[2, 46, 48]
[-0.08  0.08 -0.5 ]
[73.72773694 73.72773694 73.278     ]
[4, 25, 46]
[ 0.28 -0.28 -0.44]
[20.05630727 20.05630727 19.12928002]
[14, 28, 36]
[ 0.28 -0.28  0.32]
[91.2669711  91.2669711  89.72739348]
[14, 16, 36]
[-0.5  -0.46  0.46]
[39.665      39.45878316 39.45878316]
[23, 25, 27]
[-0.34  0.34 -0.2 ]
[67.71710966 67.71710966 64.97324338]
[17, 33, 40]
[-0.12  0.12 -0.24]
[108.50037155 108.50037155  94.47012311]
[6, 38, 44]
[-0.16  0.16  0.28]
[9.56264957 9.56264957 8.79260029]
[8, 14, 42]
[-0

[22, 28, 47]
[14, 30, 36]
[17, 25, 33]
[21, 25, 29]
[11, 13, 37]
[3, 44, 47]
[23, 27, 30]
[7, 13, 37]
[9, 17, 41]
[20, 30, 40]
[8, 16, 42]
[5, 27, 45]
[24, 26, 30]
[23, 25, 27]
[14, 25, 36]
[18, 24, 32]
[9, 31, 41]
[19, 31, 39]
[2, 4, 48]
[16, 34, 36]
[21, 25, 29]
[7, 17, 43]
[13, 34, 37]
[14, 16, 36]
[14, 25, 36]
[17, 30, 33]
[18, 32, 34]
[23, 27, 32]
[23, 27, 47]
[12, 38, 40]
[16, 34]
[17, 33, 38]
[13, 27, 37]
[16, 25, 34]
[13, 37, 41]
[15, 25, 35]
[9, 12, 38]
[13, 19, 31]
[11, 16, 34]
[16, 18, 34]
[11, 39, 41]
[13, 25, 37]
[18, 32, 35]
[18, 25, 32]
[14, 29, 36]
[15, 25, 35]
[11, 25, 39]
[16, 34, 42]
[4, 27, 46]
[19, 31, 38]
[22, 28, 40]
[10, 17, 33]
[6, 28, 44]
[21, 29, 38]
[16, 34, 38]
[17, 33, 37]
[20, 25, 30]
[10, 40, 48]
[17, 33, 37]
[3, 26, 47]
[3, 30, 47]
[15, 30, 35]
[14, 18, 32]
[9, 38, 41]
[15, 31, 35]
[13, 37, 41]
[11, 36, 39]
[16, 18, 32]
[20, 25, 30]
[22, 25, 28]
[17, 33, 46]
[10, 40, 45]
[13, 15, 35]
[15, 30, 35]
[10, 25, 40]
[3, 25, 47]
[6, 21, 29]
[23, 25, 27]
[5, 29,

number of unique ID=237
sum of bucket length=237
[-0.28  0.28 -0.44]
[143.92336741 143.92336741 142.23288483]
[14, 28, 36]
[10, 25, 40]
[11, 13, 39]
[18, 29, 32]
[18, 32, 46]
[2, 41, 48]
[10, 19, 40]
[2, 5, 48]
[7, 18, 32]
[18, 32, 42]
[20, 30, 47]
[22, 28, 46]
[7, 24, 26]
[2, 25, 48]
[16, 34, 38]
[9, 30, 41]
[16, 25, 34]
[15, 35, 45]
[23, 25, 27]
[14, 27, 36]
[3, 33, 47]
[15, 24, 35]
[5, 40, 45]
[6, 28, 44]
[19, 21, 31]
[7, 27, 43]
[21, 29, 38]
[6, 44, 47]
[4, 23, 46]
[13, 26, 37]
[14, 22, 28]
[8, 22, 42]
[14, 36, 47]
[5, 25, 45]
[17, 20, 30]
[14, 33, 36]
[20, 25, 30]
[11, 21, 29]
[2, 11, 39]
[6, 37, 44]
[7, 36, 43]
[5, 30, 45]
[19, 27, 31]
[14, 25, 36]
[17, 25, 33]
[19, 28, 31]
[20, 25, 30]
[23, 27, 30]
[10, 20, 40]
[15, 18, 32]
[22, 28, 41]
[8, 24, 42]
[7, 30, 43]
[19, 21, 31]
[21, 29, 40]
[19, 24, 26]
[7, 38, 43]
[17, 25, 33]
[24, 26, 48]
[10, 40, 44]
[22, 28, 44]
[14, 36, 41]
[21, 29, 40]
[21, 29, 44]
[13, 25, 37]
[13, 28, 37]
[18, 32, 39]
[13, 35, 37]
[18, 25, 32]
[6, 44, 47]
[13

[17, 30, 33]
[19, 25, 31]
[15, 30, 35]
[15, 33, 35]
[13, 27, 37]
[20, 30, 40]
[9, 21, 29]
[24, 26, 44]
[6, 39, 44]
[8, 25, 42]
[15, 35, 48]
[22, 28, 38]
[11, 24, 26]
[4, 18, 32]
[22, 25, 28]
[7, 35, 43]
[12, 17, 33]
[15, 35, 43]
[24, 26, 37]
[11, 14, 36]
[5, 33, 45]
[11, 25, 39]
[20, 30, 48]
[14, 29, 36]
[23, 27, 37]
[12, 30, 38]
[24, 26, 32]
[14, 36, 41]
[13, 28, 37]
[15, 22, 28]
[9, 14, 41]
[13, 19, 31]
[16, 34, 39]
[11, 25, 39]
[9, 18, 32]
[16, 27, 34]
[18, 25, 32]
[3, 9, 47]
[19, 25, 31]
[10, 40, 42]
[4, 43, 46]
[16, 25, 34]
[19, 31, 41]
[16, 24, 34]
[11, 18, 32]
[3, 43, 47]
[21, 25, 29]
[11, 39, 44]
[18, 32, 41]
[16, 34, 40]
[12, 25, 38]
[18, 32, 37]
[11, 39, 44]
[15, 20, 35]
[15, 17, 35]
[12, 27, 38]
[8, 15, 35]
[7, 38, 43]
[11, 19, 31]
[16, 24, 34]
[18, 25, 32]
[12, 24, 38]
[13, 24, 26]
[5, 22, 28]
[16, 27, 34]
[4, 25, 46]
[21, 29, 41]
[11, 28, 39]
[23, 27, 41]
[10, 25, 40]
[8, 28, 42]
[13, 21, 29]
[15, 35, 37]
[8, 13, 42]
[15, 22, 28]
[20, 30, 37]
[11, 36, 39]
[7, 38, 43]
[23, 

[5, 25, 45]
[2, 4, 46]
[13, 30, 37]
[13, 37, 48]
[4, 25, 46]
[22, 28, 45]
[7, 17, 33]
[23, 27, 46]
[15, 35, 39]
[16, 34, 38]
[11, 25, 39]
[21, 29, 46]
[9, 14, 41]
[12, 34, 38]
[18, 25, 32]
[11, 30, 39]
Data_files/U18_LIHF_itd_file.csv
number of unique ID=38
sum of bucket length=38
[-0.2   0.2  -0.34]
[72266.95592011 72266.95592011 72265.29663633]
[10, 33, 40]
[-0.32  0.32  0.36]
[119.5753865  119.5753865  114.54994822]
[16, 18, 34]
[-0.5 -0.4  0.4]
[82.257      79.73590202 79.73590202]
[20, 25, 30]
[-0.32  0.32 -0.44]
[141.48150981 141.48150981 128.44863569]
[16, 28, 34]
[-0.08  0.08 -0.12]
[69.35552464 69.35552464 67.07440073]
[4, 44, 46]
[-0.26  0.26 -0.12]
[11.57650241 11.57650241  8.6199617 ]
[13, 37, 44]
[-0.28  0.28  0.14]
[352.9551898  352.9551898  333.67874287]
[7, 14, 36]
[-0.16  0.16 -0.32]
[189.38212637 189.38212637 169.8616379 ]
[8, 34, 42]
[-0.2   0.2   0.36]
[130.1689094 130.1689094 120.2136619]
[10, 18, 40]
[-0.3   0.3  -0.16]
[226.90475225 226.90475225 216.25825556]
[15

[-0.26  0.26  0.42]
[70.75546106 70.75546106 70.58861659]
[13, 21, 37]
[-0.24  0.24  0.48]
[43.20269282 43.20269282 42.2356557 ]
[12, 24, 38]
[-0.5   0.14 -0.14]
[4.901      4.65492286 4.65492286]
[7, 25, 43]
[-0.34  0.34 -0.5 ]
[10.10784057 10.10784057  9.61      ]
[17, 25, 33]
[-0.34  0.34  0.48]
[8.09424919 8.09424919 7.00585431]
[17, 24, 33]
[-0.28  0.28 -0.08]
[76.4586668  76.4586668  75.14710315]
[14, 36, 46]
[-0.26  0.26 -0.5 ]
[14.65406335 14.65406335 14.447     ]
[13, 25, 37]
[-0.24  0.24  0.3 ]
[62.77024386 62.77024386 62.10188183]
[12, 15, 38]
[-0.4  0.4 -0.5]
[50.77670379 50.77670379 50.271     ]
[20, 25, 30]
[-0.42  0.42 -0.16]
[89.57522707 89.57522707 88.07654786]
[21, 29, 42]
[-0.28  0.28 -0.44]
[136.3778122  136.3778122  134.49593737]
[14, 28, 36]
[-0.08  0.08 -0.22]
[7.2063461  7.2063461  6.23231351]
[4, 39, 46]
[-0.32  0.32 -0.22]
[169.03533076 169.03533076 167.23885496]
[16, 34, 39]
[ 0.44 -0.44 -0.36]
[20.28062339 20.28062339 20.1566559 ]
[22, 28, 32]
[ 0.26 -0.26  

[-0.36  0.36  0.18]
[79.2098774 79.2098774 76.5582309]
[9, 18, 32]
[ 0.22 -0.22  0.12]
[244.84821888 244.84821888 244.79464296]
[6, 11, 39]
[-0.5  -0.14  0.14]
[4.003      3.70610095 3.70610095]
[7, 25, 43]
[-0.38  0.38 -0.24]
[78.2773672  78.2773672  72.07367098]
[19, 31, 38]
[ 0.4  -0.4  -0.36]
[36.12365621 36.12365621 35.68445395]
[20, 30, 32]
[-0.5 -0.2  0.2]
[22.552      16.59775022 16.59775022]
[10, 25, 40]
[ 0.14 -0.14  0.32]
[24.37607954 24.37607954 23.31932417]
[7, 16, 43]
[ 0.36 -0.36 -0.1 ]
[52.7923466  52.7923466  51.82732429]
[18, 32, 45]
[-0.24  0.24 -0.18]
[31.34989391 31.34989391 30.06628658]
[12, 38, 41]
[-0.38  0.38 -0.24]
[15.76150418 15.76150418 15.36952589]
[19, 31, 38]
[-0.38  0.38  0.14]
[36.7706423  36.7706423  34.38598567]
[7, 19, 31]
[-0.1  0.1 -0.2]
[38.45150828 38.45150828 35.40533263]
[5, 40, 45]
[ 0.4 -0.4  0.3]
[25.86509408 25.86509408 25.2428788 ]
[15, 20, 30]
[ 0.24 -0.24 -0.3 ]
[4.02961676 4.02961676 3.93385949]
[12, 35, 38]
[-0.08  0.08 -0.46]
[57.118

[-0.26  0.26 -0.06]
[92.83666243 92.83666243 81.29205537]
[13, 37, 47]
[-0.4  0.4 -0.2]
[199.80773467 199.80773467 192.65944584]
[20, 30, 40]
[-0.5   0.34 -0.34]
[218.365      186.69344666 186.69344666]
[17, 25, 33]
[ 0.28 -0.28 -0.44]
[58.38659019 58.38659019 58.31461451]
[14, 28, 36]
[ 0.22 -0.22  0.48]
[74.84462942 74.84462942 69.3684742 ]
[11, 24, 39]
[-0.2  0.2 -0.3]
[10.04489384 10.04489384  9.86407257]
[10, 35, 40]
[-0.24  0.24 -0.44]
[37.86301388 37.86301388 36.93200979]
[12, 28, 38]
[ 0.24 -0.24  0.48]
[59.58353738 59.58353738 59.12256419]
[12, 24, 38]
[-0.06  0.06 -0.24]
[69.94301384 69.94301384 69.03847601]
[3, 38, 47]
[-0.12  0.12 -0.34]
[19.88544583 19.88544583 19.5935127 ]
[6, 33, 44]
[-0.5  -0.42  0.42]
[4.228      3.53021582 3.53021582]
[21, 25, 29]
[ 0.24 -0.24 -0.48]
[41.27772969 41.27772969 40.28693606]
[12, 26, 38]
[-0.22  0.22 -0.16]
[13.04640602 13.04640602 13.03899767]
[11, 39, 42]
[ 0.28 -0.28 -0.44]
[29.69614516 29.69614516 27.82685333]
[14, 28, 36]
[ 0.24 -0.2

[-0.04  0.04 -0.36]
[18.53896697 18.53896697 18.4429725 ]
[2, 32, 48]
[-0.42  0.42  0.06]
[15.67257122 15.67257122 15.40680659]
[3, 21, 29]
[-0.44  0.44  0.34]
[5.66312922 5.66312922 5.41723235]
[17, 22, 28]
[-0.14  0.14 -0.2 ]
[8.72202492 8.72202492 8.25624338]
[7, 40, 43]
[ 0.3 -0.3 -0.2]
[39.15759229 39.15759229 37.64185881]
[15, 35, 40]
[-0.36  0.36 -0.32]
[8.60888845 8.60888845 6.24715481]
[18, 32, 34]
[-0.38  0.38  0.42]
[11.52489102 11.52489102 11.35129544]
[19, 21, 31]
[-0.18  0.18 -0.36]
[46.86174984 46.86174984 45.8773701 ]
[9, 32, 41]
[ 0.32 -0.32 -0.04]
[80.38668457 80.38668457 78.53606737]
[16, 34, 48]
[-0.5  -0.18  0.18]
[65.223      60.36059765 60.36059765]
[9, 25, 41]
[-0.5   0.22 -0.22]
[11.546      10.36466192 10.36466192]
[11, 25, 39]
[-0.38  0.38  0.18]
[13.71789828 13.71789828 11.60159462]
[9, 19, 31]
[-0.12  0.12 -0.24]
[5.36185562 5.36185562 5.22154388]
[6, 38, 44]
[-0.14  0.14 -0.28]
[17.30160545 17.30160545 17.2983405 ]
[7, 36, 43]
[-0.16  0.16 -0.08]
[5.813932

[15, 29, 35]
[10, 40, 46]
[9, 41, 43]
[3, 42, 47]
[10, 40, 48]
[4, 42, 46]
[3, 11, 47]
[7, 14, 36]
[2, 44, 48]
[12, 35, 38]
[14, 34, 36]
[24, 26, 38]
[8, 13, 37]
[23, 27, 29]
[19, 31, 34]
[10, 30, 40]
[2, 8, 48]
[18, 32, 36]
[3, 38, 47]
[16, 19, 34]
[11, 37, 39]
[14, 36, 45]
[10, 25, 40]
[8, 34, 42]
[17, 29, 33]
[16, 34, 44]
[11, 36, 39]
[7, 25, 43]
[13, 25, 37]
[19, 31, 48]
[11, 24, 26]
[6, 17, 44]
[8, 23, 27]
[6, 28, 44]
[15, 22, 35]
[3, 43, 47]
[6, 28, 44]
[2, 8, 48]
[6, 25, 44]
[16, 34, 43]
[3, 25, 47]
[10, 25, 40]
[4, 21, 46]
Data_files/U21_LIHF_itd_file.csv
number of unique ID=115
sum of bucket length=109
[ 0.38 -0.38 -0.14]
[11.93310448 11.93310448 11.30576071]
[19, 31, 43]
[ 0.4 -0.4 -0.2]
[9.85237082 9.85237082 9.73921256]
[20, 30, 40]
[-0.26  0.26  0.48]
[162.12180334 162.12180334 161.9128212 ]
[13, 24, 37]
[-0.5  -0.18  0.18]
[19.199      18.57054356 18.57054356]
[9, 25, 41]
[-0.4   0.4   0.28]
[8.79251337 8.79251337 8.55036788]
[14, 20, 30]
[-0.06  0.06 -0.5 ]
[37.5725385 3

[-0.24  0.24  0.38]
[72.56229558 72.56229558 70.50789422]
[12, 19, 38]
[-0.5 -0.3  0.3]
[38.74       33.98412996 33.98412996]
[15, 25, 35]
[-0.22  0.22 -0.4 ]
[9.10099318 9.10099318 8.42848261]
[11, 30, 39]
[-0.16  0.16  0.32]
[80.84404426 80.84404426 78.16574942]
[8, 16, 42]
[-0.3   0.3  -0.38]
[121.18907801 121.18907801 119.17542298]
[15, 31, 35]
[-0.24  0.24  0.14]
[3.58128887 3.58128887 3.4248756 ]
[7, 12, 38]
[-0.5   0.46 -0.46]
[18.592      18.35985792 18.35985792]
[23, 25, 27]
[-0.34  0.34 -0.2 ]
[7.95563289 7.95563289 6.56292971]
[17, 33, 40]
[-0.04  0.04  0.38]
[51.63942518 51.63942518 49.39070074]
[2, 19, 48]
[-0.5  -0.16  0.16]
[125.224      113.10654295 113.10654295]
[8, 25, 42]
[-0.48  0.48 -0.22]
[5.9241791  5.9241791  5.13210115]
[24, 26, 39]
[ 0.48 -0.48 -0.44]
[76.86286212 76.86286212 76.11780418]
[24, 26, 28]
[-0.34  0.34 -0.2 ]
[54.227055   54.227055   52.72438633]
[17, 33, 40]
[ 0.16 -0.16 -0.4 ]
[6.09641627 6.09641627 6.09015902]
[8, 30, 42]
[-0.08  0.08  0.46]
[16

[7, 17, 43]
[15, 35, 40]
[11, 39, 42]
[18, 32, 40]
[18, 32, 38]
[9, 41, 45]
[14, 27, 36]
[8, 36, 42]
[7, 17, 33]
[6, 26, 44]
[7, 11, 43]
[2, 13, 48]
[20, 30, 40]
[13, 15, 35]
[19, 25, 31]
[15, 17, 33]
[22, 25, 28]
[12, 38, 48]
[24, 26, 47]
[14, 25, 36]
[14, 17, 36]
[4, 22, 28]
[21, 29, 41]
[9, 25, 41]
[16, 25, 34]
[22, 28, 35]
[9, 41, 44]
[15, 17, 33]
[5, 25, 45]
[18, 30, 32]
[11, 17, 39]
[18, 32, 41]
[2, 6, 48]
[17, 33, 45]
[10, 31, 40]
[12, 25, 38]
[13, 25, 37]
[2, 39, 48]
[19, 31, 41]
[22, 28, 39]
[6, 41, 44]
[13, 37, 41]
[9, 25, 41]
[12, 25, 38]
[12, 25, 38]
[21, 29, 38]
[23, 27, 40]
[11, 33, 39]
[13, 25, 37]
[21, 29, 46]
[3, 44, 47]
[10, 30, 40]
[10, 25, 40]
[11, 25, 39]
[5, 13, 37]
[10, 25, 40]
[17, 33, 45]
[9, 34, 41]
[18, 25, 32]
[11, 25, 39]
[16, 34, 43]
[16, 34, 48]
[15, 21, 29]
[8, 25, 42]
[11, 39, 43]
[2, 25, 48]
[13, 26, 37]
[22, 25, 28]
[13, 30, 37]
[12, 31, 38]
[11, 25, 39]
[9, 32, 41]
[16, 34, 42]
[3, 20, 30]
[19, 31, 35]
[12, 24, 38]
[17, 25, 33]
[14, 36, 43]
[12, 28, 